### ISSUE TITLE
Clear Flagged Cache only when enabling and publishing an entry

### ISSUE THREAD

**Issue by john-henry** [mmikkel/CacheFlag-Craft#14]
We have a fairly large site where clearing flagged cache is quite expensive on the server.
I was thinking that we only want the the clearing to take place when an entry is published rather than have it clear each time an author resaves their entry while creating the entry.

Any ideas to where I might add this functionality or do you see any downsides to this?

**Comment by mmikkel** [comment]
Hi John-Henry, thanks for contributing! Unfortunately, no, there's no way to have CacheFlag clear caches only when an entry is published, and it's not really something I'd consider adding – the use case where you only want a flag to be cleared when an element is "published" – i.e., transitions from an unpublished state (disabled or publish date in the future) to a published state (enabled and publish date in the past) seems fairly marginal to me. Sidenote, the concept of "publishing" a post is kind of murky in Craft CMS, and t[here aren't any events for it](https://craftcms.com/docs/plugins/events-reference#entry-api-events).

My suggestion would be to use P&T's [Cold Cache](https://github.com/pixelandtonic/ColdCache) plugin instead of Cache Flag, and either clear the caches manually when you need to, or create a custom plugin for your project where you use the `beforeSaveEntry` and/or `saveEntry` events to break the caches programmatically, according to some custom logic where you determine if an entry transitioned from "unpublished" to "published".
